"""add feed_source and feed_item

Revision ID: 7b3f9c1d2e4a
Revises: ea5a329d5f07
Create Date: 2026-07-03 09:12:41.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


revision: str = '7b3f9c1d2e4a'
down_revision: str | None = 'ea5a329d5f07'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sa.Enum('GITHUB', 'RSS', name='feedkind'), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['feed_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_feed_items_source_external')
    )
    op.create_index(op.f('ix_feed_items_source_id'), 'feed_items', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feed_items_source_id'), table_name='feed_items')
    op.drop_table('feed_items')
    op.drop_table('feed_sources')
    # Dropping feed_sources does not drop the ENUM type Postgres created
    # implicitly in upgrade(). Drop it explicitly so downgrade + upgrade
    # works. checkfirst makes this a no-op on SQLite, which has no enum types.
    bind = op.get_bind()
    sa.Enum(name='feedkind').drop(bind, checkfirst=True)
    # ### end Alembic commands ###
