"""add closed_at to issues

Revision ID: ea5a329d5f07
Revises: 1abf75f50b75
Create Date: 2026-07-02 14:59:47.856113

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


revision: str = 'ea5a329d5f07'
down_revision: str | None = '1abf75f50b75'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'closed_at')
    # ### end Alembic commands ###
